using System.ComponentModel;
using System.Windows.Forms;
using Autofac;
using Xperters.Admin.UI.Common;

namespace Xperters.Admin.UI.Tabs.ErrorWarningTab
{
    public partial class ErrorWarningView : UserControl, IErrorWarningView
	{

		public ErrorWarningView()
		{
			if (LicenseManager.UsageMode != LicenseUsageMode.Designtime)
			{
				Presenter = ContainerOperations
					.Container
					.Resolve<ErrorWarningPresenter>(new TypedParameter(typeof(IErrorWarningView), this));
			}

			InitializeComponent();
			// This line of code is generated by Data Source Configuration Wizard
			ErrorWarningGridView.DataSource = ErrorsWarnings;
		}

		public BindingList<ErrorWarning> ErrorsWarnings { get; private set; } = new BindingList<ErrorWarning>();

		private ErrorWarningPresenter Presenter { get; set; }

		private void ClearItemClick(object sender, System.EventArgs e)
		{
			Presenter.ClearErrorsCommand.Execute();
		}

		public void MakeVisible()
		{
			if (Parent?.Parent is TabControl tab)
			{
				tab.SelectedTab = tab.TabPages[1];
			}
		}

	}
}
